jdhert/view_project

pet_test/package-lock.json, pet_test/package.json, pet_test/src/components/FreeBoard.vue, pet_test/src/components/FreeBoardModal.vue, pet_test/src/components/LoginView.vue, pet_test/src/components/NavBar.vue
=>  - 자유 게시판 DB 끌어오기 + 모달구현

pet_test/src/components/FreeBoard2.vue, pet_test/src/components/HelloWorld.vue, pet_test/src/components/LoginView.vue, pet_test/src/components/MyPage.vue, pet_test/src/components/NavBar.vue
=> - view 전체적으로 부족한 부분 수정

pet_test/src/components/MyPage.vue
=>  마이 페이지 동적으로 정보 가져오기

pet_test/src/assets/css/style-myPage.css, pet_test/src/components/MyPage.vue
* mypagae.vue 파일에서 v-for문으로 동물 카드를 반복해서 뽑아낼 시에 발생하는 카드 배치 문제 해결
* 로그인 안하고 마이페이지에 접근할 시에 로그인하라는 알림창 뜨게 하고, 로그인 페이지로 보내는 코드 추가
=> MyPage.vue 문제 해결/코드 보완

pet_test/src/components/AddQuestionBoard.vue, pet_test/src/components/Asd.vue, pet_test/src/components/CreateDiary.vue, pet_test/src/components/LoginView.vue, pet_test/src/components/MyPage.vue, pet_test/src/router/router.js
=> 질문게시판 등록 및 마이페이지 보완

pet_test/src/components/FreeBoard3.vue, pet_test/src/components/detailFreeBoard.vue
=> 2024-03-04 완

pet_test/src/components/FreeBoard3.vue, pet_test/src/components/LoginView.vue, pet_test/src/components/detailFreeBoard.vue
freeboard 작성자에 해당하는 유저만 게시글 수정, 삭제 가능하도록 기능 구현 진행 중
=> #detailfreeboard ms

pet_test/src/components/AddQuestionBoard.vue
=> 질문게시판 Create 기능 추가

pet_test/src/components/QuestionBoard.vue, pet_test/src/components/QuestionBoardModal.vue
=> 찐막 2024-03-06(완)

pet_test/src/components/detailFreeBoard.vue
=> 댓글 삭제 후 새로고침 이슈 수정 완료

pet_test/src/App.vue, pet_test/src/components/CreateDiary.vue, pet_test/src/components/MyPage.vue, pet_test/src/components/PetActivity.vue, pet_test/src/components/PetCalendar.vue, pet_test/src/components/PetDiary.vue, pet_test/src/components/bmi.vue, pet_test/src/components/carousel.vue
=> - pet crousel 데이터 불러오기 완료 (날짜 불러오기 나중에 수정 예정)

node_modules/.package-lock.json, package-lock.json, pet_test/package-lock.json, pet_test/package.json, pet_test/src/components/FreeBoard3.vue, pet_test/src/components/detailFreeBoard.vue
detailfreeboard
_게시글 좋아요, 좋아요 취소, 하트아이콘 상태유지
_전체 레이아웃 재변경
_엑스버튼 수정
freeboard3
_url 막아두기
=> detailfreeboard

node_modules/@fullcalendar/daygrid/internal.cjs, pet_test/src/components/CreateDiary.vue, pet_test/src/components/Editcarousel.vue, pet_test/src/components/PetCalendar.vue, pet_test/src/components/PetDiary.vue, pet_test/src/components/carousel.vue, pet_test/src/router/router.js
- Editcarousel.vue 추가 (수정하기까지 완료)
- 갤러리(diary) mounted 메소드 수정 (id의 값 변경)
- 갤러리 페이지(diary)에서 해당 일지 클릭시 미리보기 페이지(carouel)로 이동 (해당 일지의 데이터 불러옴)
=> - carousel에서 수정하기 버튼 추가

pet_test/public/index.html, pet_test/src/components/AddPhotoBoard.vue, pet_test/src/components/FreeBoard3.vue, pet_test/src/components/LoginView.vue, pet_test/src/components/MyPage.vue, pet_test/src/components/NavBar.vue, pet_test/src/components/PetActivity.vue, pet_test/src/main.js, pet_test/vue.config.js
=> 펫 액티비티 이미지 구글 place api 연동중

pet_test/src/components/PetActivity.vue, pet_test/vue.config.js
=> 2024-03-13 (완)

pet_test/src/components/AddPhotoBoard.vue, pet_test/src/components/CreateDiary.vue, pet_test/src/components/Editcarousel.vue, pet_test/src/components/PetCalendar.vue, pet_test/src/components/PetDiary.vue, pet_test/src/components/carousel.vue
- carousel 페이지 수정한 사진 업데이트
- Editcarousel 페이지 삭제, 추가 하기
=> - diary 페이지 이미지 불러오기

pet_test/src/components/LoginView.vue, pet_test/src/components/PetActivity.vue
=> 2024-03-18 (완)

pet_test/src/components/FindPassword.vue, pet_test/src/components/LoginView.vue, pet_test/src/components/MyFeed.vue, pet_test/src/components/MyPage.vue, pet_test/src/components/UpdatePw.vue, pet_test/src/router/router.js
=> - 비밀번호 찾기 (임시 비밀번호 이메일 전송)

pet_test/src/components/FreeBoard3.vue, pet_test/src/components/PetActivity.vue
=> 펫 액티비티 수정 진행중..

pet_test/src/components/PetActivity.vue, pet_test/vue.config.js
=> 펫 액티비티 이미지 부여 완료

pet_test/src/components/AddPhotoBoard.vue, pet_test/src/components/AddQuestionBoard.vue, pet_test/src/components/CreateDiary.vue, pet_test/src/components/DeleteUser.vue, pet_test/src/components/FindPassword.vue, pet_test/src/components/MyFeed.vue, pet_test/src/components/PetCalendar.vue, pet_test/src/components/PetDiary.vue, pet_test/src/components/SignUp.vue, pet_test/src/components/UpdatePw.vue, pet_test/src/components/UserUpdate.vue, pet_test/src/components/carousel.vue
=> 로그인 + 비밀번호 찾기 메일로 코드 입력하도록 구현

pet_test/Dockerfile, pet_test/nginx.conf, pet_test/package-lock.json, pet_test/package.json, pet_test/src/components/HelloWorld.vue, pet_test/src/components/PetActivity.vue
=> docker 올리기 위해 수정

pet_test/src/App.vue, pet_test/src/assets/css/style.css, pet_test/src/components/DeleteUser.vue, pet_test/src/components/DetailActivity.vue, pet_test/src/components/LoginView.vue, pet_test/src/components/MyFeed.vue, pet_test/src/components/MyPage.vue, pet_test/src/components/NavBar2.vue, pet_test/src/components/PetDetail.vue, pet_test/src/components/PetDiary.vue, pet_test/src/components/UserUpdate.vue
=> - 액티비티 페이지 북마크 추가

pet_test/src/components/AddPhotoBoard.vue, pet_test/src/components/AddQuestionBoard.vue, pet_test/src/components/EditFreeBoard.vue, pet_test/src/components/EditQuestionBoard.vue, pet_test/src/components/FreeBoard3.vue, pet_test/src/components/QuestionBoard.vue, pet_test/src/components/QuestionBoardModal.vue, pet_test/src/components/ReplyComponent.vue, pet_test/src/components/detailFreeBoard.vue
freeboard, qnaboard 관련페이지들
전체적인 에러 코드 수정 및 추가
=> freeboard, qnaboard 전체적인 에러 코드 수정 및 추가

pet_test/src/assets/css/style.css, pet_test/src/components/AddPhotoBoard.vue, pet_test/src/components/AddQuestionBoard.vue, pet_test/src/components/EditFreeBoard.vue, pet_test/src/components/EditQuestionBoard.vue, pet_test/src/components/Footer.vue, pet_test/src/components/Footer2.vue, pet_test/src/components/FreeBoard3.vue, pet_test/src/components/HelloWorld.vue, pet_test/src/components/PetActivity.vue, pet_test/src/components/QuestionBoard.vue, pet_test/src/components/QuestionBoardImageModal.vue, pet_test/src/components/QuestionBoardModal.vue, pet_test/src/components/ReplyComponent.vue, pet_test/src/components/detailFreeBoard.vue, pet_test/src/router/router.js
freeboard, qnaboard 관련 페이지 이슈 해결
welcomepage, footer 수정
=> freeboard, qnaboard 관련 페이지 이슈 해결

pet_test/src/components/AddQuestionBoard.vue, pet_test/src/components/Footer.vue, pet_test/src/components/QuestionBoard.vue, pet_test/src/components/QuestionBoardModal.vue, pet_test/src/components/ReplyComponent.vue, pet_test/src/components/detailFreeBoard.vue, pet_test/src/components/detailQnaBoard.vue, pet_test/src/router/router.js
qnaboard, freeboard, footer 관련 오류 수정 및 배치 수정
=> qnaboard, freeboard, footer 관련 오류 수정 및 배치 수정

pet_test/src/components/PetDiary.vue, pet_test/src/components/SignUp.vue, pet_test/src/components/UserUpdate.vue
=>  - 회원가입 페이지 수정

pet_test/src/components/FreeBoard3.vue, pet_test/src/components/detailFreeBoard.vue, pet_test/src/components/detailQnaBoard.vue
게시글 좋아요 이슈 해결
_freeboard
_qnaboard
=> 게시글 좋아요 이슈 해결

pet_test/src/assets/css/style.css, pet_test/src/components/DetailActivity.vue, pet_test/src/components/PetActivity.vue, pet_test/src/components/PetDiary.vue
=> - pet Diary 페이지네이션 수정
